export enum ENUM_SHIPPING_ID {
  NHANH = 5001,
  TIET_KIEM = 5002,
  HOA_TOC = 5003,
  VIETTEL_POST = 5111,
  NINJA_VAN = 5112,
  GIAO_HANG_NHANH = 5113,
  VNPOST_TIET_KIEM = 5222,
  SPX_EXPRESS = 5333,
  AhaMove = 5444,
}

export enum NAME_SHIPPING_METHOD {
  NHANH = 'NHANH',
  TIET_KIEM = 'Tiết Kiệm',
  HOA_TOC = 'Hỏa Tốc',
  VIETTEL_POST = ' VIETTEL_POST',
  NINJA_VAN = 'NINJA_VAN',
  GIAO_HANG_NHANH = 'GIAO_HANG_NHANH',
  VNPOST_TIET_KIEM = 'VNPOST_TIET_KIEM',
  SPX_EXPRESS = 'SPX_EXPRESS',
  AhaMove = 'AhaMove ',
}
