/* eslint-disable no-unused-vars */
export enum EMicroservice {
  GATEWAY_USER_SERVICE = 'GATEWAY_USER_SERVICE',
  GATEWAY_SERVICE = 'GATEWAY_SERVICE',
  GATEWAY_TOKEN_SERVICE = 'GATEWAY_TOKEN_SERVICE',
  GATEWAY_AUTH_SERVICE = 'GATEWAY_AUTH_SERVICE',
  GATEWAY_ROLE_SERVICE = 'GATEWAY_ROLE_SERVICE',
}

export enum EKafkaGroup {
  USER_GROUP = 'USER_GROUP',
  GATEWAY_GROUP = 'GATEWAY_GROUP',
  TOKEN_GROUP = 'TOKEN_GROUP',
  AUTH_GROUP = 'AUTH_GROUP',
  ROLE_GROUP = 'ROLE_GROUP',
}
export enum EKafkaMessage {
  REQUEST_LOGIN = 'REQUEST_LOGIN',
  REQUEST_CREATE_USER = 'REQUEST_CREATE_USER',
  REQUEST_SEND_VERIFY_EMAIL = 'REQUEST_SEND_VERIFY_EMAIL',
  REQUEST_VERIFY_EMAIL = 'REQUEST_VERIFY_EMAIL',
  REQUEST_USER_BY_ID = 'REQUEST_USER_BY_ID',
}
